Odometry readjustement
robotique-ecam/cdfr pull request #31
Opened 2021-02-25 10:31 UTC by PhileasL

# Merging PR #30 and  #29

2021-02-25 10:47 UTC, PhileasL commented on src/modules/robot/param/robot.in.yml
> +        inflate_around_unknown: false
Theses layers will be used for cups obstacles.

2021-02-25 10:47 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.dictionary_index_id = {"0":0, "1":0, "2":0}
Again, maybe rework this dictionary relating to comment on PR #29

2021-02-25 20:47 UTC, 3wnbr1 commented on src/modules/robot/robot/interfaces.py
> +                        output={'both': 'log'},
What's the behavior on this one ?

2021-02-25 20:50 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.allie = "obelix" if self.get_namespace().strip("/") == "asterix" else "asterix"
An ally, some allies

2021-02-25 20:55 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +    def initObstaclesArray(self):
Please use black to maintain code quality and enforce its use. Might add a CI check for it
```
pip3 install black
cd <repo-root-dir>
black .
```

2021-02-25 20:58 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.simulation = True if machine() != "aarch64" else False
Could be nice to create a function `is_simulation` or even `is_this_reality`  dans un package et l'utiliser partout pour detecter la simu. ARM64 will become more common in the future and this limits code duplication

2021-02-25 21:01 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.previous_obstacles = copy.deepcopy(self.obstacles)
`self.obstacles.copy()` should be implemented, has the same behavior and eases readability

2021-02-25 21:03 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        return float(t1.sec - t2.sec + (t1.nanosec - t2.nanosec)*1e-9)
Already a float
```python
return t1.sec - t2.sec + (t1.nanosec - t2.nanosec)*1e-9
```

2021-02-25 21:14 UTC, 3wnbr1 requested changes

2021-02-25 21:14 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        for ennemie_marker in msg.markers:
Aie aie aie....
`enemy` and `enemies`

2021-02-25 21:14 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.dictionary_index_id = {"0":0, "1":0, "2":0}
Consider rework, is a dict best suited ? Just in case keys can be any object, not only string

2021-02-25 21:14 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +                if not in_dict:
Consider refactoring this part, harsh to understand

2021-02-25 22:21 UTC, PhileasL commented on src/modules/robot/robot/interfaces.py
> +                        output={'both': 'log'},
In order to re-adjust the odometry, we need to get the transformation between "map" and "odom", to achieve it, we're calling [`tfBuffer.canTransform` in drive](https://github.com/robotique-ecam/cdfr/blob/f62e12ebac210e9ece70a46e5413793e024d858b/src/modules/drive/src/drive.cpp#L139).

The problem of this call is that it's dropping a bunch of `Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist` waiting for the transformation initiated by [localisation_node](https://github.com/robotique-ecam/cdfr/blob/f62e12ebac210e9ece70a46e5413793e024d858b/src/modules/localisation/localisation/localisation_node.py#L117)

By specifying `output={'both': 'log'},` the log of drive node won't appear anymore in the terminal. 

It's a bit of a nasty method, but I haven't found anything that will simply prevent this warning from appearing.

2021-02-25 22:22 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.allie = "obelix" if self.get_namespace().strip("/") == "asterix" else "asterix"
**A low level of English implies a low level of responsibilities**

2021-02-25 22:27 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        return float(t1.sec - t2.sec + (t1.nanosec - t2.nanosec)*1e-9)
Indeed it's a bit redundant

2021-02-25 22:45 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.simulation = True if machine() != "aarch64" else False
#33

2021-02-25 22:47 UTC, 3wnbr1 commented on src/modules/robot/robot/interfaces.py
> +                        output={'both': 'log'},
Disagreed. And what happens if you want to debug drive ?

2021-02-25 23:16 UTC, PhileasL commented on src/modules/robot/robot/interfaces.py
> +                        output={'both': 'log'},
Just re-enable the log by `output="screen",`, but tf2 will spam the warning message until localisation_node initiates the tf and the log will become unreadable during this period.
If the node crash, it appears on the terminal even if `output={'both': 'log'},`.
If you know a good alternative of this thing feel free to modify it !

2021-02-26 09:37 UTC, 3wnbr1 commented on src/modules/robot/robot/interfaces.py
> +                        output={'both': 'log'},
I agree on the garbage part, however cutting off the logs in no proper way of handling it.
The spamming is due to an exception raised in `canTransform(...)`

See example below to catch exceptions
https://github.com/ros2/geometry2/blob/ros2/tf2_ros/src/tf2_echo.cpp

For now revert to `output="screen"`, open an issue and I will fix in separate PR

2021-02-26 09:50 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +                if not in_dict:
I'll use an array like `self.enemies_markers_ids = [0, 0]` instead of a dictionary, it's a lot more clear.

2021-02-26 10:28 UTC, 3wnbr1 requested changes

2021-02-26 10:28 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.enemies_subscription_
Why those two lines ?

2021-02-26 10:28 UTC, 3wnbr1 commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
Better to make one / a few blocks per function. Not one block per line

2021-02-26 10:47 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.enemies_subscription_
By reading the documentation, it was meant to prevent a warning from appearing but i just tested the package without theses lines and nothing like described in the documentation appears. I'll consider removing them, and others that i put in other packages for the same reason.

2021-02-26 10:52 UTC, PhileasL commented on src/navigation/teb_obstacles/teb_obstacles/teb_obstacles.py
> +        self.previous_obstacles = copy.deepcopy(self.obstacles)
I'm not sure how to do it tho. Any clue ?

2021-02-26 11:29 UTC, PhileasL commented on src/modules/robot/robot/interfaces.py
> +                        output={'both': 'log'},
#34

2021-02-26 15:00 UTC, 3wnbr1 approved these changes

2021-02-26 15:50 UTC, merged