Custom nav2 behavior tree
robotique-ecam/cdfr pull request #36
Opened 2021-03-09 22:43 UTC by PhileasL

# Purpose

The purpose of this PR is for the robot to automatically choose what movement to do considering the goal and its current pose (position / orientation).

The robot have to move **linearly and as much perpendicular to the wall as possible in specific area** (by specific area i mean near walls and in ports).

# How ?

For this need, we'll need 2 things :
- Another controller but slower and more accurate,
- Reshaping the navigation behavior tree.

# Another controller

Well, TEB controller is pretty cool, why not reuse the same but slower and more accurate ? That's what have been done.
The second controller is shaped for displacement in specific areas, in can get as close to obstacles as 0.5 cm.

# Reshaping the navigation behavior tree

The [readme](https://github.com/robotique-ecam/cdfr/blob/de025a084878fff4ca53378fef71960fe11cd920/src/navigation/bt_custom_plugins/README.md) from the bt_custom_plugins describes itself pretty well.

2021-03-09 23:11 UTC, PhileasL reviewed
- [ ] Check if a specific controller can use a specific goal_checker_plugin.
- [ ] Use `!defaultsvalues`
- [ ] Rename controllers
- [ ] Check dependencies
- [ ] Clean code (remove commentaries, logs, ...)

2021-03-09 23:11 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/include/split_goal_action.hpp
> +#include "nav_msgs/msg/path.hpp"
Dependencies.

2021-03-09 23:11 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/package.xml
> +  <exec_depend>lifecycle_msgs</exec_depend>
Dependencies.

2021-03-09 23:11 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +#include "behaviortree_cpp_v3/decorator_node.h"
Dependencies.

2021-03-09 23:11 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +    RCLCPP_WARN(node_->get_logger(), "q_out z: %f, w: %f", q_out.z, q_out.w);
Remove debugging log.

2021-03-09 23:11 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +  // check orientation ?
So, the response ?
No, assuming the goal orientation in specific area is in [0, 90, 180, 270]° orientation.

2021-03-09 23:34 UTC, 3wnbr1 requested changes
Amazing 👍

2021-03-09 23:34 UTC, 3wnbr1 commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +    if ( (abs(q_out.z - 0.7071068)<0.22 &&  abs(q_out.w - 0.7071068)<0.22)
Use a `const float var = 0.7071068` damn ! 😂
Same for `.22`

2021-03-10 22:47 UTC, PhileasL commented
I'd like to be able to specify specific areas, exit area coordinates and distance from walls into a yml file.

- [ ] Check the feasibility

2021-03-12 15:50 UTC, 3wnbr1 approved these changes

2021-03-12 15:51 UTC, 3wnbr1 commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +    if ( (abs(q_out.z - 0.7071068)<0.22 &&  abs(q_out.w - 0.7071068)<0.22)
@PhileasL just fix that one before merging

2021-03-12 18:13 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +    if ( (abs(q_out.z - 0.7071068)<0.22 &&  abs(q_out.w - 0.7071068)<0.22)
Yes, i'm not forgetting, i'm not done with dependencies either

2021-03-12 18:52 UTC, PhileasL commented on src/navigation/bt_custom_plugins/bt_split_goal/src/split_goal_action.cpp
> +    if ( (abs(q_out.z - 0.7071068)<0.22 &&  abs(q_out.w - 0.7071068)<0.22)
[bt_split_goal const float](https://github.com/robotique-ecam/cdfr/pull/36/commits/8280c7d8f247f57d076912db2d3bfb1d1a8c7068)

2021-03-12 18:56 UTC, 3wnbr1 approved these changes

2021-03-12 19:02 UTC, merged