Strategix
robotique-ecam/cdfr pull request #39
Opened 2021-03-19 14:51 UTC by mAxYoLo01

## Purpose

The goal of this PR is to reformat most of Cetautomatix and Strategix nodes, as they were poorly written in the previous year

## Details of what has changed
- Created an Action class as well as all its children to represent all possible types of Actions. This allows for better customization and much better comprehension of the entire codebase
- Temporarily removed most actions, to put them back one by one once they are done. Currently present: Phare & Pavillon
- Merged Score class with the Strategix node (useless class on its own)
- **BIG** change: New Robot class with much more readable functions (seeing the difference between base and custom functions), trying to separate some actions in their own class. Old Robot class still present in the old_robot.py for the moment.

2021-03-19 15:15 UTC, PhileasL approved these changes
Approve for the moment, I'll review it properly later. @mAxYoLo01 can continue his work this afternoon.

2021-03-19 15:22 UTC, 3wnbr1 requested changes
Nice effort 👍

2021-03-19 15:22 UTC, 3wnbr1 commented on src/assurancetourix/strategix/strategix/actions.py
> +# }
Why ?! 😂🆘

2021-03-19 15:22 UTC, 3wnbr1 commented on src/assurancetourix/strategix/strategix/action_objects/action.py
> +class Action:
Add a docstring to document that this is an abstract base class

2021-03-19 15:22 UTC, 3wnbr1 commented on src/assurancetourix/strategix/strategix/action_objects/manche_air.py
> +    def get_initial_position(self, robot):
Add docstring

2021-03-19 15:22 UTC, 3wnbr1 commented on src/assurancetourix/strategix/strategix/action_objects/manche_air.py
> +    def start_actuator(self, robot):
Same

2021-03-19 15:22 UTC, 3wnbr1 commented on src/assurancetourix/strategix/strategix/strategix.py
> +        #     self.score += 0
Again ?

2021-03-19 15:22 UTC, 3wnbr1 commented on src/modules/cetautomatix/cetautomatix/old_robot.py
> +        #             self.drop = NC
No

2021-03-19 15:22 UTC, 3wnbr1 commented on src/modules/cetautomatix/cetautomatix/old_robot.py
> +#!/usr/bin/env python3
Drop the file if you don't use it anymore. Git is there for you

2021-07-03 17:24 UTC, 3wnbr1 approved these changes
Congratz

2021-07-03 17:35 UTC, merged