ODrive
robotique-ecam/cdfr pull request #46
Opened 2021-05-30 23:42 UTC by PhileasL

# Purpose

This PR deals with the implementation of [ODrive](https://odriverobotics.com/) into drive node.

## What as been done ?

- Modification of drive node (from rad/s to turns/s),
- Implementation of a custom odrive library,
- odrive_ros sub-module deletion.

### Custom odrive library

This library is based on the work of [Framework-Robotics-GmbH](https://github.com/Framework-Robotics-GmbH). They come with a [ros2 node](https://github.com/Framework-Robotics-GmbH/odrive-ros2-node) that can communicates really easily with ODrive hardware using a serial communication. We [refactored this node](https://github.com/robotique-ecam/odrive-ros2-node) for it to stick to our architecture standards. By putting this node in our code base, we realized that it wasn't really a thing for a simple serial communication to have its own dedicated node.

So, we decided to transform this node into a [library](https://github.com/robotique-ecam/cdfr/blob/ODrive/src/modules/drive/include/ODrive.hpp) and use it directly from drive node.

As a simple serial communication through USB, we're expecting it to work pretty well. But in reality it's not the case. We were having some trouble when asking to ODrive to send a checksum with its message, 75% of messages returned will not have this checksum. We'll further investigate the problem in the future but for the moment, we're considering a simple check on the message length in order to validate it.

### Drive node modifications

As ODrive returning turns/s values, we've just modified all the formulas by switching from rad/s to turns/s. Navigation through simulation isn't broken, if simulation mode is enabled, we haven't forgotten to adapt the data into what simulation requires as input or returns.

We also add a gearbox ratio into formulas and the capability to change left motor as right motor and vice-versa without having to modify the wiring.

### YAML new parameters

- `odrive_usb_port` --> string --> the usb odrive port, ex: `odrive_usb_port: "/dev/ttyS1"`
- `invert_wheel` --> boolean --> the capability of changing right motor to left and vice versa, ex: `invert_wheel: false`
- `gearbox_ratio` --> float --> the gearbox ratio between motors and wheels, ex `gearbox_ratio: 8.75`

2021-05-31 10:14 UTC, 3wnbr1 requested changes
Good implementation, few changes requested and would be much better to move the sliders code into actuators node

2021-05-31 10:14 UTC, 3wnbr1 commented on src/modules/localisation/localisation/vlx/sensors_sim.py
> +        if int(t) != 0:
No if statement, refactor to use `int((t - int(t)) * 1e9)` instead which doesn't fault for `t = 0`

2021-05-31 10:14 UTC, 3wnbr1 commented on src/modules/drive/src/drive.cpp
>    this->declare_parameter("i2c_bus");
Remove I2C if not used

2021-05-31 10:14 UTC, 3wnbr1 commented on src/modules/drive/src/drive.cpp
>  #define I2C_ADDR_SLIDER 0x12
Sliders / actuators shall be moved to a separate node now that there is no more I2C required by drive. Was created like this to have only one process accessing the file descriptor `/dev/i2c1`

2021-05-31 10:14 UTC, 3wnbr1 commented on src/modules/drive/src/ODrive.cpp
> +std::pair<float, float> ODrive::getPosition_Velocity(const int motor)
NIT : Method naming convention

2021-05-31 10:14 UTC, 3wnbr1 commented on src/modules/drive/include/drive.hpp
>  #include "i2c.hpp"
See comment below about integrating Sliders / actuators into a separate node

2021-05-31 12:56 UTC, PhileasL commented on src/modules/localisation/localisation/vlx/sensors_sim.py
> +        if int(t) != 0:
Yep, haven't thought about it

2021-05-31 13:00 UTC, PhileasL commented
As it's not concerning ODrive, what about dedicating another PR for the separation sliders / actuators from drive  ?

2021-05-31 14:07 UTC, 3wnbr1 commented
> As it's not concerning ODrive, what about dedicating another PR for the separation sliders / actuators from drive ?

Agreed, you can strip either strip it now or in the dedicated PR

2021-06-01 07:08 UTC, 3wnbr1 approved these changes

2021-06-01 11:10 UTC, PhileasL commented
> Agreed, you can strip either strip it now or in the dedicated PR

Yep, it'll have its dedicated PR which will also contains a bunch of overall modifications for physical robots to work.

2021-06-01 11:10 UTC, merged